SuporteSF.UI.MVC/Controllers/AdministracaoController.cs
using SuporteSF.Application.Interfaces;
using SuporteSF.Application.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace SuporteSF.UI.MVC.Controllers
{
    public class AdministracaoController : Controller
    {
        private readonly ISuporteAppService _suporteApp;

        public AdministracaoController(ISuporteAppService suporteApp)
        {
            _suporteApp = suporteApp;
        }

        // GET: Administracao
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListaSuporte(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Código" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var tab = _suporteApp.GetAll(); //db2.Suportes.AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                tab = tab.Where(s => s.Descricao.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Descrição":
                    tab = tab.OrderBy(s => s.Descricao);
                    break;
                case "Slug":
                    tab = tab.OrderBy(s => s.Descricao);
                    break;
                default:
                    tab = tab.OrderBy(s => s.Descricao);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(tab.ToPagedList(pageNumber, pageSize));
        }



        public ActionResult _DetalhesSuporte(int id = 0)
        {
            var model = _suporteApp.GetByIdTipoInteiro(id);
            return PartialView(model);
        }

        public ActionResult Cancelar2(int id = 0)
        {
            var model = _suporteApp.GetByIdTipoInteiro(id);

            //model.status = "Cancelado";
            //model.data_alteracao = DateTime.Now;
            //model.data_fechamento = DateTime.Now;
            //model.idusuario_alteracao = User.Identity.GetUserId();

            //if (ModelState.IsValid)
            //{
            //    db2.Entry(model).State = EntityState.Modified;
            //    db2.SaveChanges();
            //    TempData["Success"] = "Cancelamento feito com sucesso!";
            //    //return RedirectToAction("Acompanhar");
            //}
            //else
            //{
            //    TempData["Erro"] = "Erro ao cancelar. Favor tentar novamente!";
            //}

            return RedirectToAction("ListaSuporte");
        }



        // POST: Tab_Suporte/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Salvar([Bind(Include = "idsuporte,status,data_alteracao,idusuario_alteracao,descr_solucao")] SuporteViewModel suporteViewModel)
        {
            var model = _suporteApp.GetByIdTipoInteiro(suporteViewModel.IdSuporte);
            //if (model != null)
            //{
            //    if (!model.Status.ToUpper().Equals("ABERTO"))
            //        ModelState.AddModelError(string.Empty, "É Necessário estar com suporte em aberto para alteração.");
            //    else
            //    {
            //        try
            //        {
            //            model.descr_solucao = suporteViewModel.descr_solucao;
            //            model.data_atendimento = suporteViewModel.data_alteracao;
            //            model.data_alteracao = suporteViewModel.data_alteracao;
            //            model.idusuario_alteracao = suporteViewModel.idusuario_alteracao;

            //            db2.Entry(suporte).State = EntityState.Modified;
            //            db2.SaveChanges();
            //            TempData["Success"] = "feito com sucesso!";
            //        }
            //        catch
            //        {
            //            TempData["Erro"] = "Erro ao salvar. Favor tentar novamente!";
            //            //ModelState.AddModelError(string.Empty, "Ocorreu um erro. Favor tentar novamente.");
            //            //return View(suporte);
            //        }
            //    }
            //}
            //else
            //{
            //    TempData["Erro"] = "Erro. Favor tentar novamente!";
            //}

            return RedirectToAction("ListaSuporte");
        }


        public ActionResult Delete(int id)
        {
            var model = _suporteApp.GetByIdTipoInteiro(id);
            return RedirectToAction("Delete", "Suporte", new { id = id });
        }
    }
}

SuporteSF.UI.MVC/Views/Administracao/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

SuporteSF.UI.MVC/Views/Administracao/ListaSuporte.cshtml
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using PagedList.Mvc;
@model PagedList.IPagedList<SuporteSF.Application.ViewModels.SuporteViewModel>


@{
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

@section Styles {
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/global/plugins/select2/select2.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/assets/global/plugins/datatables/extensions/Scroller/css/dataTables.scroller.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/assets/global/plugins/datatables/extensions/ColReorder/css/dataTables.colReorder.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
    <!-- END PAGE LEVEL STYLES -->
    <!-- Theme styles START -->
    <link href="~/Content/assets/global/css/plugins.css" rel="stylesheet">
    <!-- Theme styles END -->
}

<div class="main">
    <div class="container">

        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-20">
            <!-- BEGIN CONTENT -->
            <div class="col-md-12 col-sm-12">
                <h1>Lista de Chamados</h1>
                <div class="alert alert-messages">
                </div>
                <div class="content-page">
                    <div class="row">
                        <div class="col-md-12 ">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-gift"></i> Chamados
                                    </div>

                                </div>
                                <div class="portlet-body">
                                    <div class="dataTables_wrapper">
                                        <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                            <thead>
                                                <tr>
                                                    <th class="col-md-1">
                                                        @Html.DisplayName("Código")
                                                    </th>
                                                    <th class="col-md-5">
                                                        @Html.DisplayName("Descrição")
                                                    </th>
                                                    <th class="col-md-2">
                                                        @Html.DisplayName("Data Abertura")
                                                    </th>
                                                    <th class="col-md-2">
                                                        @Html.DisplayName("Status")
                                                    </th>
                                                    <th class="col-md-2">
                                                        &nbsp;
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.IdSuporte)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Descricao)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.DtAbertura)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Status)
                                                        </td>
                                                        <td class="text-left">
                                                            @Html.ActionLink("Detalhes", "_DetalhesSuporte", "Administracao", null, new { id = @item.IdSuporte, @class = "btn green btn-xs edit-person" })

                                                            @{
                                                    if (item.Status.ToUpper().Equals("ABERTO"))
                                                    {
                                                        @Html.ActionLink("Cancelar", "Cancelar2", "Administracao", new { id = @item.IdSuporte }, new { @class = "btn red btn-xs", onclick = "return confirm('Are you sure?');" })
                                                    }
                                                            }

                                                            @Html.ActionLink("Apagar", "Delete", "Administracao", new { id = @item.IdSuporte }, new { @class = "btn green btn-xs" })
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>

                                        <div class="row">
                                            <div class="col-md-5 col-sm-12">
                                                <div class="dataTables_info" role="status" aria-live="polite">
                                                    Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                                                    of @Model.PageCount
                                                </div>
                                            </div>
                                            <div class="col-md-7 col-sm-12">
                                                <div class="dataTables_paginate paging_simple_numbers">
                                                    @Html.PagedListPager(Model, page => Url.Action("Busca",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
                                  PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions
                                  {
                                      HttpMethod = "POST",
                                      OnBegin = "$('#myModal').modal('show');",
                                      OnComplete = "$('#myModal').modal('hide');",
                                      OnFailure = "alert('Falha')",
                                      UpdateTargetId = "gridInterno",
                                      InsertionMode = InsertionMode.Replace
                                  }))
                                                </div>
                                            </div>
                                        </div>


                                    </div>

                                </div>

                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
                </div>
                <!-- END CONTENT -->
            </div>
            <!-- END SIDEBAR & CONTENT -->
        </div>
    </div>
</div>

<div class="modal  fade in" id="edit-person" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div id="edit-person-container" class="modal-dialog"></div>
</div>




@section scripts {
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="~/Content/assets/global/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/extensions/ColReorder/js/dataTables.colReorder.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/extensions/Scroller/js/dataTables.scroller.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
    <script src="~/Content/assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script><!-- pop up -->
    <script src="~/Content/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/admin/pages/scripts/table-advanced.js"></script>
    <script src="~/Content/assets/global/plugins/jquery.pulsate.min.js" type="text/javascript"></script>
}

@section scripts2 {
    <script type="text/javascript">
        jQuery(document).ready(function () {
            //TableAdvanced.init();
        });


    </script>



    <script type="text/javascript">
        var mensagem_sucesso = '@TempData["Success"]';
        var mensagem_erro = '@TempData["Erro"]';

        if (mensagem_sucesso != "") {
            showAndDismissAlert('success', mensagem_sucesso);
        }

        if (mensagem_erro != "") {
            showAndDismissAlert('danger', mensagem_erro);
        }

        function showAndDismissAlert(type, message) {
            var htmlAlert = '<div class="note note-' + type + '">' + message + '</div>';

            // Prepend so that alert is on top, could also append if we want new alerts to show below instead of on top.
            $(".alert-messages").prepend(htmlAlert);

            if (type == "success") {
                $('.alert-messages').pulsate({
                    color: "#fdbe41",
                    reach: 50,
                    repeat: 7,
                    speed: 200,
                    glow: true
                });
            }

            // Since we are prepending, take the first alert and tell it to fade in and then fade out.
            // Note: if we were appending, then should use last() instead of first()
            $(".alert-messages .note").first().hide().fadeIn(200).delay(4000).fadeOut(1000, function () { $(this).remove(); });
        }



    function teste()
    {
        e.preventDefault();
        var r = confirm("Press a button!");
        if (r == true) {
            return true;
        } else {
            return false;
        }
    }


    $(function () {

        ////Optional: turn the chache off
        //$.ajaxSetup({ cache: false });

        $('.edit-person').click(function () {
            //var url = "/Bootstrap/EditPerson"; // the url to the controller
            var id = $(this).attr('id');

            $('#edit-person-container').load(this.href + '/' + id, function () {
                $('#edit-person').modal({
                    backdrop: 'static',
                    keyboard: true
                }, 'show');
                bindForm(this);
            });
            return false;
        });
    });

    function bindForm(dialog) {
        $('form', dialog).submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    $('#edit-person').modal('hide');
                    //if (result.success) {
                    //    $('#edit-person').modal('hide');
                    //    // Refresh:
                    //    // location.reload();
                    //} else {
                    //    $('#edit-person-container').html(result);
                    //    bindForm();
                    //}
                }
            });
            return false;
        });
    }
    </script>


}
<!-- END PAGE LEVEL JAVASCRIPTS -->

SuporteSF.UI.MVC/Views/Administracao/_DetalhesSuporte.cshtml
@using Microsoft.AspNet.Identity
@model SuporteSF.Application.ViewModels.SuporteViewModel

<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel">Detalhes do Chamado: @Model.IdSuporte</h3>
    </div>
    <div>
        @using (Html.BeginForm("Salvar", "Administracao", FormMethod.Post, new { role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.IdSuporte)
            @Html.HiddenFor(model => model.DtAlteracao, new { @Value=System.DateTime.Now.ToString("dd/MM/yyyy") })
            @Html.HiddenFor(model => model.IdUsuarioAlteracao, new { @Value = User.Identity.GetUserId() })

            <div class="form-horizontal  modal-body">
                <table border="0" align="center" cellpadding="0" cellspacing="0" class="table table-striped table-bordered">
                    <tr>
                        <td><strong>Data de Abertura:</strong> @Html.DisplayFor(model => model.DtAbertura)</td>
                    </tr>
                    <tr>
                        <td><strong>Data de Atendimento:</strong> @Html.DisplayFor(model => model.DtAtendimento)</td>
                    </tr>
                    <tr>
                        <td><strong>Data de Fechamento:</strong> @Html.DisplayFor(model => model.DtFechamento)</td>
                    </tr>
                    <tr>
                        <td><strong>Descrição do Chamado:</strong> @Html.DisplayFor(model => model.Descricao)</td>
                    </tr>
                    <tr>
                        <td><strong>Status:</strong> @Html.DisplayFor(model => model.Status)</td>
                    </tr>
                    <tr>
                        <td><strong>Prioridade:</strong> @Html.DisplayFor(model => model.Prioridade)</td>
                    </tr>
                    <tr>
                        <td><strong>Sistema Operacional:</strong> @Html.DisplayFor(model => model.SistemaOperacional)</td>
                    </tr>
                    <tr>
                        <td><strong>Problema Recorrente:</strong> @Html.DisplayFor(model => model.ProblemaRecorrente)</td>
                    </tr>
                    <tr>
                        <td><strong>E-mail:</strong> @Html.DisplayFor(model => model.Email)</td>
                    </tr>
                    <tr>
                        <td><strong>Telefone:</strong> @Html.DisplayFor(model => model.DddTelefone) - @Html.DisplayFor(model => model.Telefone)</td>
                    </tr>
                    <tr>
                        <td><strong>Melhor Horário:</strong> @Html.DisplayFor(model => model.MelhorHorarioAtendimento)</td>
                    </tr>
                    <tr>
                        <td><strong>Usuário Contribuiu em agradecimento:</strong> @Html.DisplayFor(model => model.ValorContribuicao)</td>
                    </tr>
                    <tr>
                        <td><strong>Solução para o Problema:</strong>@{ if (Model.Status.ToUpper().Equals("ABERTO"))
                                                                        { @Html.TextAreaFor(model => model.DescricaoSolucao, new { rows = "3" }) } else { @Html.DisplayFor(model => model.DescricaoSolucao) } } </td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer ">
                <button type="submit" class="btn blue">Salvar</button>
                <button class="btn  btn-default" data-dismiss="modal" aria-hidden="true">Fechar</button>
            </div>
        }

    </div>
</div>