SuporteSF.UI.MVC/Controllers/SuporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SuporteSF.Application.Interfaces;
using SuporteSF.Application.ViewModels;
using PagedList;


using SuporteSF.Infra.CrossCutting.Identity;
using SuporteSF.Infra.CrossCutting.Identity.Context;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace SuporteSF.UI.MVC.Controllers
{
    public class SuporteController : Controller
    {
        private readonly ISuporteAppService _suporteApp;

        public SuporteController(ISuporteAppService suporteApp)
        {
            _suporteApp = suporteApp;
        }

        // GET: Suporte
        public ActionResult Index()
        {
            return View(_suporteApp.GetAll());
        }

        // GET: Suporte/Details/5
        public ActionResult Details(int id)
        {
            var suporteViewModel = _suporteApp.GetByIdTipoInteiro(id);
            return View(suporteViewModel);
        }

        // GET: Suporte/Create
        public ActionResult Create()
        {
            //ViewBag.FornecedorId = new SelectList(_fornecedorApp.GetAll(), "FornecedorId", "Nome");
            return View();
        }

        // POST: Suporte/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SuporteViewModel suporteViewModel)
        {
            if (ModelState.IsValid)
            {
                _suporteApp.Add(suporteViewModel);
                return RedirectToAction("Index");
            }

            //ViewBag.FornecedorId = new SelectList(_fornecedorApp.GetAll(), "FornecedorId", "Nome", produtoViewModel.FornecedorId);
            return View(suporteViewModel);
        }

        // GET: Suporte/Edit/5
        public ActionResult Edit(int id)
        {
            var suporteViewModel = _suporteApp.GetByIdTipoInteiro(id);
            //ViewBag.FornecedorId = new SelectList(_fornecedorApp.GetAll(), "FornecedorId", "Nome", produtoViewModel.FornecedorId);
            return View(suporteViewModel);
        }

        // POST: Suporte/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SuporteViewModel suporteViewModel)
        {
            if (ModelState.IsValid)
            {
                _suporteApp.Update(suporteViewModel);
                return RedirectToAction("Index");
            }

            //ViewBag.ClienteId = new SelectList(_fornecedorApp.GetAll(), "ClienteId", "Nome", produtoViewModel.FornecedorId);
            return View(suporteViewModel);
        }

        // GET: Suporte/Delete/5
        public ActionResult Delete(int id)
        {
            var suporteViewModel = _suporteApp.GetByIdTipoInteiro(id);
            return View(suporteViewModel);
        }

        // POST: Suporte/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _suporteApp.Remove(_suporteApp.GetByIdTipoInteiro(id));
            return RedirectToAction("Index");
        }







        public ActionResult Solicitar()
        {
            return View();
        }



        // POST: Tab_Suporte/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Solicitar([Bind(Include = "Descricao,SistemaOperacional,ProblemaRecorrente,Prioridade,Email,DddTelefone,Telefone,MelhorHorarioAtendimento,Status,FlgTermoAceito,DtAbertura,IdUsuarioCadastro")] SuporteViewModel suporteViewModel)
        {
            if (ModelState.IsValid)
            {
                if (!suporteViewModel.FlgTermoAceito)
                    ModelState.AddModelError(string.Empty, "É Necessário concordar com os termos de suporte remoto.");
                else
                {
                    _suporteApp.Add(suporteViewModel);
                    
                    //try
                    //{
                    //    db2.Suportes.Add(tab_Suporte);
                    //    db2.SaveChanges();
                    //}
                    //catch
                    //{
                    //    ModelState.AddModelError(string.Empty, "Ocorreu um erro. Favor tentar novamente.");
                    //    return View(suporteViewModel);
                    //}

                    return RedirectToAction("Acompanhar");
                }
            }
            else
            {
                //ModelState.AddModelError(string.Empty, "Ocorreu um erro.");
            }

            return View(suporteViewModel);
        }


        public ActionResult Acompanhar(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Código" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var tab = _suporteApp.GetAll(); //db2.Suportes.AsQueryable();
            if (!String.IsNullOrEmpty(searchString))
            {
                tab = tab.Where(s => s.Descricao.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Descrição":
                    tab = tab.OrderBy(s => s.Descricao);
                    break;
                case "Slug":
                    tab = tab.OrderBy(s => s.Descricao);
                    break;
                default:
                    tab = tab.OrderBy(s => s.Descricao);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(tab.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult Detalhes2(int id = 0)
        {
            var suporteVielModel = _suporteApp.GetByIdTipoInteiro(id);
            return PartialView(suporteVielModel);
        }


        public ActionResult Cancelar2(int id = 0)
        {
            var model = _suporteApp.GetByIdTipoInteiro(id);
            if (ModelState.IsValid)
            {
                _suporteApp.CancelarSuporte(model, new Guid(User.Identity.GetUserId()));
                return RedirectToAction("Acompanhar");
            }
            return View("Acompanhar");
            

            //if (ModelState.IsValid)
            //{
            //    //db2.Entry(model).State = EntityState.Modified;
            //    //db2.SaveChanges();
            //    //return RedirectToAction("Acompanhar");
            //}
            //return View("Acompanhar");
        }
    }
}

SuporteSF.UI.MVC/Views/Suporte/Acompanhar.cshtml
@using SuporteSF.Infra.CrossCutting.Identity
@using SuporteSF.Infra.CrossCutting.Identity.Context
@using Microsoft.AspNet.Identity
@using Microsoft.AspNet.Identity.EntityFramework
@using PagedList.Mvc;
@model PagedList.IPagedList<SuporteSF.Application.ViewModels.SuporteViewModel>


@{
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

@section Styles {
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/global/plugins/select2/select2.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/assets/global/plugins/datatables/extensions/Scroller/css/dataTables.scroller.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/assets/global/plugins/datatables/extensions/ColReorder/css/dataTables.colReorder.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css" />
    <!-- END PAGE LEVEL STYLES -->
    <!-- Theme styles START -->
    <link href="~/Content/assets/global/css/plugins.css" rel="stylesheet">
    <!-- Theme styles END -->
}

<div class="main">
    <div class="container">

        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-20">
            <!-- BEGIN CONTENT -->
            <div class="col-md-12 col-sm-12">
                <h1>Acompanhar Suporte</h1>
                <div class="content-page">
                    <div class="row">
                        <div class="col-md-12 ">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        @{
                                            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new IdentityContext()));
                                            var user = userManager.FindById(User.Identity.GetUserId());
                                            //ViewBag.CurrentUser = user;
                                        }
                                        <i class="fa fa-gift"></i> Chamados do usuário: <div class="bold inline">@{if (user != null){ @user.Nome } }</div>
                                    </div>

                                </div>
                                <div class="portlet-body">
                                    <div class="dataTables_wrapper">
                                        <table class="table table-striped table-bordered table-hover dataTable no-footer">
                                            <thead>
                                                <tr>
                                                    <th class="col-md-1">
                                                        @Html.DisplayName("Código")
                                                    </th>
                                                    <th class="col-md-5">
                                                        @Html.DisplayName("Descrição")
                                                    </th>
                                                    <th class="col-md-2">
                                                       @Html.DisplayName("Data Abertura")
                                                    </th>
                                                    <th class="col-md-2">
                                                        @Html.DisplayName("Status")
                                                    </th>
                                                    <th class="col-md-2">
                                                        &nbsp;
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.IdSuporte)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Descricao)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.DtAbertura)
                                                        </td>
                                                        <td>
                                                            @Html.DisplayFor(modelItem => item.Status)
                                                        </td>
                                                        <td class="text-left">
                                                            @Html.ActionLink("Detalhes", "Detalhes2", "Suporte", null, new { id = @item.IdSuporte, @class = "btn green btn-xs edit-person" })

                                                            @{
                                                                if (item.Status.ToUpper().Equals("ABERTO"))
                                                                {
                                                                    @Html.ActionLink("Cancelar", "Cancelar2", "Suporte", new { id = @item.IdSuporte }, new { @class = "btn red btn-xs", onclick = "return confirm('Are you sure?');" })
                                                                }
                                                            }
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                       
                                        <div class="row">
                                            <div class="col-md-5 col-sm-12">
                                                <div class="dataTables_info" role="status" aria-live="polite">
                                                    Página @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
                                                    of @Model.PageCount
                                                </div>
                                            </div>
                                            <div class="col-md-7 col-sm-12">
                                                <div class="dataTables_paginate paging_simple_numbers">
                                                    @Html.PagedListPager(Model, page => Url.Action("Busca",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
                                  PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions
                                  {
                                      HttpMethod = "POST",
                                      OnBegin = "$('#myModal').modal('show');",
                                      OnComplete = "$('#myModal').modal('hide');",
                                      OnFailure = "alert('Falha')",
                                      UpdateTargetId = "gridInterno",
                                      InsertionMode = InsertionMode.Replace
                                  }))
                                                </div>
                                            </div>
                                        </div>


                                    </div>

                                </div>

                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
                </div>
                <!-- END CONTENT -->
            </div>
            <!-- END SIDEBAR & CONTENT -->
        </div>
    </div>
</div>

<div class="modal  fade in" id="edit-person" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div id="edit-person-container" class="modal-dialog"></div>
</div>




@section scripts {
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script type="text/javascript" src="~/Content/assets/global/plugins/select2/select2.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/extensions/TableTools/js/dataTables.tableTools.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/extensions/ColReorder/js/dataTables.colReorder.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/extensions/Scroller/js/dataTables.scroller.min.js"></script>
    <script type="text/javascript" src="~/Content/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>
    <!-- END PAGE LEVEL PLUGINS -->
    <!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->
    <script src="~/Content/assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script><!-- pop up -->
    <script src="~/Content/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <script src="~/Content/assets/admin/pages/scripts/table-advanced.js"></script>
}

@section scripts2 {
    <script type="text/javascript">
        jQuery(document).ready(function () {
            //TableAdvanced.init();
        });

       
    </script>



<script type="text/javascript">

    function teste()
    {
        e.preventDefault();
        var r = confirm("Press a button!");
        if (r == true) {
            return true;
        } else {
            return false;
        }
    }


    $(function () {

        ////Optional: turn the chache off
        //$.ajaxSetup({ cache: false });

        $('.edit-person').click(function () {
            //var url = "/Bootstrap/EditPerson"; // the url to the controller
            var id = $(this).attr('id');

            $('#edit-person-container').load(this.href + '/' + id, function () {
                $('#edit-person').modal({
                    backdrop: 'static',
                    keyboard: true
                }, 'show');
                bindForm(this);
            });
            return false;
        });
    });

    function bindForm(dialog) {
        $('form', dialog).submit(function () {
            $.ajax({
                url: this.action,
                type: this.method,
                data: $(this).serialize(),
                success: function (result) {
                    $('#edit-person').modal('hide');
                    //if (result.success) {
                    //    $('#edit-person').modal('hide');
                    //    // Refresh:
                    //    // location.reload();
                    //} else {
                    //    $('#edit-person-container').html(result);
                    //    bindForm();
                    //}
                }
            });
            return false;
        });
    }
</script>


}
<!-- END PAGE LEVEL JAVASCRIPTS -->

SuporteSF.UI.MVC/Views/Suporte/Detalhes.cshtml
<p>
    <span class="glyphicon glyphicon-warning-sign"></span>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    Donec consequat nisl a nibh tincidunt condimentum.
    Nullam in augue vitae augue dictum eleifend.
    Nunc porta fermentum metus, quis efficitur lectus scelerisque ac.
    Quisque egestas sit amet nunc in interdum.
    Etiam malesuada maximus nisi, id tempus metus.
    Vivamus at sapien ut metus aliquet sodales sed id magna.
    Integer in auctor ex. Phasellus tempor, est vel placerat dapibus,
    nulla dui tempor ligula, at pulvinar libero nunc gravida metus.
    Proin non feugiat felis. Proin ut ultrices ex. Morbi aliquet lacinia elit at bibendum.
    Nunc facilisis, neque a finibus dignissim, turpis felis vulputate diam,
    a tristique tellus nibh nec nulla. Suspendisse eget augue non turpis
    dignissim euismod eget eget odio. Donec sit amet nibh cursus, efficitur
    nibh in, sodales arcu. Pellentesque pulvinar consequat lacus ac porttitor.
</p>
    @using (Html.BeginForm("Index", "Home", FormMethod.Post))
    {
        <div class="row">
            &nbsp;
        </div>
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                    Cancel
                </button>
                <button type="submit" id="approve-btn"
                        class="btn btn-danger">
                    Save
                </button>
            </div>
        </div>
    }

SuporteSF.UI.MVC/Views/Suporte/Solicitar.cshtml
@using Microsoft.AspNet.Identity
@model SuporteSF.Application.ViewModels.SuporteViewModel

@{
    Layout = "~/Views/Shared/_LayoutInterno.cshtml";
}

@section Styles {
    <!-- BEGIN PAGE LEVEL STYLES -->
    <link href="~/Content/assets/global/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet">
    <link href="~/Content/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css">
    <!-- END PAGE LEVEL STYLES -->
    <!-- Theme styles START -->
    <link href="~/Content/assets/global/css/plugins.css" rel="stylesheet">
    <!-- Theme styles END -->
}

<div class="main">
    <div class="container">
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-20">
            <!-- BEGIN CONTENT -->
            <div class="col-md-12 col-sm-12">
                <h1>Solicitar Suporte</h1>
                <div class="content-page">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="note note-success">
                                <h4 class="bold">ATENÇÃO</h4>
                                <p class="text-justify">
                                    Precisamos que descreva com riqueza de detalhes o problema que está apresentando. Caso não seja possível realizar o reparo online, iremos descrever o problema identificado para que procure um técnico local.
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <!-- BEGIN SAMPLE FORM PORTLET-->
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-gift"></i> Preencha o formulário abaixo
                                    </div>

                                </div>
                                <div class="portlet-body form">
                                    @using (Html.BeginForm("Solicitar", "Suporte", FormMethod.Post, new { role = "form" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        @Html.ValidationSummary("", new { @class = "text-danger" })
                                        
                                        @Html.HiddenFor(model => model.Status, new { @Value = "Aberto" })
                                        @Html.HiddenFor(model => model.DtAbertura, new { @Value = System.DateTime.Now.ToString("dd/MM/yyyy") })
                                        @Html.HiddenFor(model => model.IdUsuarioCadastro, new { @Value = User.Identity.GetUserId() })
                  
                                        <div class="form-body">
                                            <div class="form-group">
                                                <label>Descreva o problema com detalhes</label><span class="color-red"> *</span>
                                                @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control", @rows = 3 })
                                            </div>
                                            <div class="form-group">
                                                <label>Qual seu sistema operacional?</label>
                                                @{
                                                    var itens_so = new SelectList(
                                                        new List<SelectListItem>
                                                        {
                                                            new SelectListItem { Text = "Windows", Value = "Windows"},
                                                            new SelectListItem { Text = "Linux", Value = "Linux"},
                                                            new SelectListItem { Text = "Mac", Value = "Mac"}
                                                        }, "Value", "Text");
                                                }
                                                @Html.DropDownListFor(model => model.SistemaOperacional, itens_so, new { @class = "form-control" })
                                            </div>
                                            <div class="form-group">
                                                <label>O problema é recorrente?</label>
                                                @{
                                                    var itens_recorrente = new SelectList(
                                                        new List<SelectListItem>
                                                        {
                                                            new SelectListItem { Text = "Não", Value = "Não"},
                                                            new SelectListItem { Text = "Sim", Value = "Sim"}
                                                        }, "Value", "Text");
                                                }
                                                @Html.DropDownListFor(model => model.ProblemaRecorrente, itens_recorrente, new { @class = "form-control" })
                                            </div>
                                            <div class="form-group">
                                                <label>Qual é a prioridade do chamado?</label>
                                                @{
                                                var itens_prioridade = new SelectList(
                                                    new List<SelectListItem>
                                                        {
                                                            new SelectListItem { Text = "Baixa", Value = "Baixa"},
                                                            new SelectListItem { Text = "Normal", Value = "Normal"},
                                                            new SelectListItem { Text = "Alta", Value = "Alta"},
                                                            new SelectListItem { Text = "Urgente", Value = "Urgente"}
                                                        }, "Value", "Text");
                                                }
                                                @Html.DropDownListFor(model => model.Prioridade, itens_prioridade, new { @class = "form-control" })
                                            </div>
                                            <div class="form-group">
                                                <label>Confirme seu endereço de e-mail</label><span class="color-red"> *</span>
                                                <div class="form-group">
                                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @placeholder = "E-mail" })
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label>Telefone FIXO com DDD para contato</label><span class="color-red"> *</span>
                                                <div class="input-group">
                                                    @Html.TextBoxFor(model => model.DddTelefone, new { @id = "ddd_telefone", @class = "form-control input-xsmall", @placeholder = "DDD" })
                                                    @Html.TextBoxFor(model => model.Telefone, new { @id= "telefone", @class = "form-control input-small", @placeholder = "Telefone FIXO" })
                                                </div>
                                                <div class="form-group">
                                                    <label>Escolha o melhor horário para o atendimento</label>
                                                    <div class="form-group">
                                                        @Html.TextBoxFor(model => model.MelhorHorarioAtendimento, new { @class = "form-control", @placeholder = "Escolha o melhor horário para o atendimento" })
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="alert alert-warning text-justify">
                                                <strong>ATENÇÃO.</strong> Nós consideramos algumas ações necessárias para realizar uma limpeza completa do computador, incluindo a remoção de softwares listados abaixo sem solicitar permissão ao usuário.<br>- Baidu Antivirus<br>- PSafe<br>- Adwares - Programas que substituem sua página inícial
                                                <i class="icon icon-alerts-01"></i>
                                            </div>
                                            <div class="form-info">
                                                <div class="checkbox-list">
                                                    <label>
                                                        @Html.CheckBoxFor(model => model.FlgTermoAceito) ACEITO OS TERMOS DE SUPORTE REMOTO
                                                    </label>
                                                </div>
                                            </div>
                                            <div class="form-actions">
                                                <button type="submit" class="btn blue">Solicitar</button>
                                                <button type="reset" class="btn default">Limpar campos</button>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                            <!-- END SAMPLE FORM PORTLET-->
                        </div>
                    </div>

                </div>
                <!-- END CONTENT -->
            </div>
            <!-- END SIDEBAR & CONTENT -->
        </div>
    </div>
</div>

@section scripts {
    <!-- BEGIN PAGE LEVEL PLUGINS -->
    <script src="~/Content/assets/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script><!-- pop up -->
    <script src="~/Content/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.inputmask/jquery.inputmask.js" type="text/javascript"></script>
    <!-- BEGIN PAGE LEVEL SCRIPTS -->
}

@section scripts2 {
    <script type="text/javascript">
        $(document).ready(function () {
            $("#ddd_telefone").inputmask("99");
            //$("#telefone").inputmask("999999999999");
            $("#telefone").inputmask("99999999[999]");
            //$(selector).inputmask("mask", { "mask": "(999) 999-9999" }); //specifying fn & options
            //$(selector).inputmask({ "mask": "99-9999999" }); //specifying options only
            //$(selector).inputmask("9-a{1,3}9{1,3}"); //mask with dynamic syntax 
        });
    </script>
}

<!-- END PAGE LEVEL JAVASCRIPTS -->